import { GoogleGenAI } from '@google/genai';
import { EmailCase } from '@/src/types/index.ts';

let aiClient: GoogleGenAI | null = null;

function getAiClient(): GoogleGenAI | null {
  if (!aiClient && process.env.GEMINI_API_KEY) {
    aiClient = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  return aiClient;
}

export async function askInvestigationCopilot(
  emailCase: EmailCase,
  userQuestion: string,
  history: { role: 'user' | 'assistant'; content: string }[] = []
): Promise<{ answer: string; citedEvidenceIds: string[]; source: 'GEMINI_AI' | 'DETERMINISTIC_COPILOT' }> {
  const evidenceSummary = emailCase.evidenceList
    .map(e => `[${e.id}] (${e.type}, Reliability: ${e.reliability}): ${e.title} - ${e.observation}`)
    .join('\n');

  const hopsSummary = emailCase.relayHops
    .map(h => `Hop #${h.index}: IP ${h.ip} | ASN ${h.asn} (${h.asnOrg}) | Trusted: ${h.isTrusted ? 'YES' : 'NO (Untrusted lowest/origin)'} | Flags: ${h.flags.join(', ')}`)
    .join('\n');

  const systemInstruction = `You are the TRACE-X Evidence-Grounded SOC Copilot for SIH26106 (Email Threat Detection & Forensic Intelligence).

ROLE & CORE PURPOSE:
You interpret deterministic forensic evidence and analyses generated by the TRACE-X pipeline. You provide concise, defensible, evidence-grounded reports for SOC analysts.

STRICT FORENSIC RULES & CRITICAL CONSTRAINTS:
1. NO HALLUCINATIONS / INVENTION: Never invent an IP address, domain name, URL, authentication result (SPF/DKIM/DMARC), campaign relationship, timestamp, or other forensic fact. Only use what is explicitly provided.
2. NO MANUAL SCORE CALCULATION: Never attempt to calculate or recompute threat scores or evidence reliability weights. Only report the deterministic values provided in the context.
3. NO OVERRIDING DETERMINISTIC RESULTS: Do not override or contradict the deterministic forensic results (verdict, threat scoring, reliability assessments) calculated by TRACE-X.
4. EVIDENCE ID GROUNDING: Every factual claim or deduction MUST cite one or more TRACE-X evidence IDs in square brackets, e.g., [EV-01], [EV-02]. Do not make claims without a corresponding evidence ID.
5. SUFFICIENCY CHECK: If evidence is insufficient for any finding, campaign relationship, or interpretation, explicitly state "Insufficient evidence." for that point.
6. GEOLOCATION HYPOTHESIS BOUNDARY: Infrastructure geolocation (city, country, ASN) must always be described purely as hosting/transit infrastructure context. NEVER describe or refer to an IP's location as proof of the attacker's physical identity or physical location.
7. SEPARATION OF CONCEPTS: Clearly distinguish observed evidence facts from your logical interpretations and tactical recommendations.

RESPONSE STRUCTURE REQUIREMENTS:
Format your response using the following sections where applicable (use markdown bold headers). Keep your analysis concise, professional, and tailored for a SOC analyst:

- **Evidence-supported findings**: Summarize key findings directly backed by evidence items. List the specific evidence IDs (e.g., [EV-01]) supporting each.
- **Counter-evidence**: Detail any evidence or facts that contradict a malicious assessment or support legitimacy (e.g., SPF/DKIM passes). If none exist, state "None observed."
- **Recommended next steps**: Provide highly specific, actionable recommendations (such as DNS firewall block, token revocation, endpoint isolation, tenant mailbox sweeps) based on the case facts.
- **Uncertainty**: Call out areas where data is missing, inconclusive, or requires further validation. If evidence is lacking, state "Insufficient evidence for [topic]."
- **Evidence IDs used**: List all TRACE-X evidence IDs cited in your response (e.g., EV-01, EV-03).

CURRENT CASE FACTS:
- Case Number: ${emailCase.caseNumber}
- Subject: "${emailCase.subject}"
- From: "${emailCase.senderName}" <${emailCase.senderAddress}>
- Recipient: <${emailCase.recipientAddress}>
- Stated Attack Type: ${emailCase.attackType}
- Verdict: ${emailCase.decision.verdict} (Severity: ${emailCase.decision.threatSeverity}, Confidence: ${emailCase.decision.threatConfidence}%, Evidence Quality: ${emailCase.decision.evidenceQuality}%)
- SPF: ${emailCase.authAnalysis.spf.status} | DKIM: ${emailCase.authAnalysis.dkim.status} | DMARC: ${emailCase.authAnalysis.dmarc.status}
- Display Name Spoofed: ${emailCase.authAnalysis.displaySpoofing.isSpoofed}
- Reply-To Mismatch: ${emailCase.authAnalysis.replyToMismatch.hasMismatch} (${emailCase.authAnalysis.replyToMismatch.replyTo})

COLLECTED FORENSIC EVIDENCE ITEMS:
${evidenceSummary}

RECONSTRUCTED RELAY HOPS:
${hopsSummary}

DECISION ANALYSIS DETECTED:
Why Suspicious/Malicious:
${emailCase.decision.why.map(w => `- ${w}`).join('\n')}
Counter-Evidence:
${emailCase.decision.whyNot.map(w => `- ${w}`).join('\n')}
`;

  const client = getAiClient();

  if (client) {
    try {
      const response = await client.models.generateContent({
        model: 'gemini-3.8-flash',
        contents: userQuestion,
        config: {
          systemInstruction,
          temperature: 0.1, // Low temperature to maximize factual precision and constraint compliance
        },
      });

      const text = response.text || 'Unable to generate analysis from model output.';
      // Extract cited evidence tags like [EV-01]
      const citedIds = Array.from(new Set((text.match(/EV-\d{2}/g) || []).map(id => id)));

      return {
        answer: text,
        citedEvidenceIds: citedIds,
        source: 'GEMINI_AI',
      };
    } catch (err) {
      console.warn('Gemini API call failed, falling back to deterministic copilot engine:', err);
    }
  }

  // Deterministic fallback engine fully structured under correct headers
  const fallback = getDeterministicFallback(emailCase, userQuestion);
  return {
    answer: fallback.answer,
    citedEvidenceIds: fallback.citedEvidenceIds,
    source: 'DETERMINISTIC_COPILOT',
  };
}

function getDeterministicFallback(
  emailCase: EmailCase,
  question: string
): { answer: string; citedEvidenceIds: string[] } {
  const qLower = question.toLowerCase();
  let findings = '';
  let counter = 'None observed.';
  let nextSteps = '';
  let uncertainty = 'None flagged.';
  const citedIds: string[] = [];

  if (qLower.includes('why') || qLower.includes('suspicious') || qLower.includes('malicious') || qLower.includes('threat')) {
    findings = `Email is evaluated as suspicious by deterministic security filters. Key findings:\n` +
      emailCase.decision.why.map((w, idx) => `- ${w} [EV-0${idx + 1}]`).join('\n');
    
    if (emailCase.decision.whyNot.length > 0) {
      counter = emailCase.decision.whyNot.map(w => `- ${w}`).join('\n');
    }
    
    nextSteps = `1. Revoke active user session tokens for ${emailCase.recipientAddress}.\n2. Submit identified indicators (domains/IPs) to firewalls.`;
    uncertainty = `Earliest transit relays are untrusted and subject to spoofing by client-side headers prior to edge receipt.`;
    emailCase.evidenceList.forEach(e => { if (e.supportsThreat) citedIds.push(e.id); });
  } 
  else if (qLower.includes('supports') || qLower.includes('supporting')) {
    findings = `The following cryptographic evidence records support the high threat rating:\n` +
      emailCase.evidenceList.filter(e => e.supportsThreat).map(e => `- [${e.id}] (${e.title}): ${e.observation}`).join('\n');
    
    nextSteps = `Verify corresponding logs in the EDR console and block matching DNS destinations.`;
    uncertainty = `Indicator ratings represent static rulesets and need to be contextualized with active business agreements.`;
    emailCase.evidenceList.forEach(e => { if (e.supportsThreat) citedIds.push(e.id); });
  }
  else if (qLower.includes('contradicts') || qLower.includes('contradict') || qLower.includes('legit')) {
    findings = `Observable findings that suggest legitimacy or protocol conformance:\n` +
      `- SPF Validation: ${emailCase.authAnalysis.spf.status}\n` +
      `- DKIM Validation: ${emailCase.authAnalysis.dkim.status}\n` +
      `- DMARC Validation: ${emailCase.authAnalysis.dmarc.status}`;
    
    if (emailCase.decision.whyNot.length > 0) {
      findings += `\n` + emailCase.decision.whyNot.map(w => `- ${w}`).join('\n');
      emailCase.evidenceList.filter(e => !e.supportsThreat).forEach(e => citedIds.push(e.id));
    } else {
      findings += `\nNo active evidence records contradict the assessment.`;
    }
    
    counter = emailCase.decision.why.map(w => `- ${w}`).join('\n');
    nextSteps = `Perform secondary out-of-band contact to verify authenticity of business flow.`;
    uncertainty = `Authentication protocol passes do not eliminate risk from hijacked accounts or fast-flux hosting nodes.`;
  }
  else if (qLower.includes('infrastructure') || qLower.includes('ip') || qLower.includes('domain')) {
    findings = `Earliest observed sending hop is node **${emailCase.relayHops[0]?.ip}** under ASN **${emailCase.relayHops[0]?.asnOrg || 'Unknown ASN'}**.\n` +
      `- Location context: ${emailCase.relayHops[0]?.country || 'Unknown'}\n` +
      `- Domain in question: ${emailCase.urls[0]?.domain || 'None detected'}`;
    
    citedIds.push('EV-03');
    nextSteps = `1. Restrict perimeter access to IP ${emailCase.relayHops[0]?.ip} and flag its hosting provider.\n2. Invalidate M365 tokens of affected users.`;
    uncertainty = `Earliest hop geolocation defines hosting infrastructure context, NOT verified physical location of the threat actor.`;
  }
  else if (qLower.includes('campaign') || qLower.includes('correlated') || qLower.includes('connect')) {
    if (emailCase.linkedCampaignId) {
      findings = `Connected to active threat campaign cluster **${emailCase.linkedCampaignId}**.\n` +
        `- Linkage rationale: Matches fast-flux domain pools and display-name spoofing pattern.\n` +
        `- Organization exposure: ${emailCase.affectedUsersCount} other targeted users detected.`;
      citedIds.push('EV-04');
      nextSteps = `Initiate immediate sweep of tenant mailboxes for display name "${emailCase.senderName}" or subject matching "${emailCase.subject}".`;
    } else {
      findings = `Insufficient evidence. No registered threat campaign cluster matches this case fingerprint.`;
    }
    uncertainty = `Campaign correlation is heuristic; shared transit relays are common among benign bulk mailers.`;
  }
  else if (qLower.includes('next') || qLower.includes('investigate') || qLower.includes('step') || qLower.includes('action')) {
    findings = `Defensible next steps calculated for **${emailCase.attackType}** incidents:`;
    nextSteps = `1. **Identity Protection**: Revoke Microsoft 365 tokens for ${emailCase.recipientAddress} and mandate password/MFA refresh.\n` +
      `2. **Perimeter Block**: Submit fast-flux IPs and domains (${emailCase.urls[0]?.domain || emailCase.senderAddress}) to DNS firewall.\n` +
      `3. **Forensic Tracking**: Map earliest observable node IP ${emailCase.relayHops[0]?.ip || 'origin'} [EV-03] and flag associated ASN.`;
    citedIds.push('EV-01', 'EV-03');
    uncertainty = `Investigation steps are generic playbooks and should match local enterprise response workflows.`;
  }
  else if (qLower.includes('change') || qLower.includes('assessment')) {
    findings = `The current assessment would be changed by the following factors:\n` +
      `- Confirmed out-of-band validation from the genuine domain representative.\n` +
      `- Realignment of internal display name headers with verified SMTP sources.`;
    nextSteps = `Initiate out-of-band communication with target recipient and sender.`;
    uncertainty = `Automated telemetry cannot evaluate subjective context or off-system business authorizations.`;
    citedIds.push('EV-01', 'EV-02');
  }
  else {
    findings = `Automated analysis for case **${emailCase.caseNumber}**:\n` +
      `- Verdict: ${emailCase.decision.verdict} (${emailCase.decision.threatConfidence}% Confidence)\n` +
      `- Severity: ${emailCase.decision.threatSeverity}\n` +
      `- Evidence Quality: ${emailCase.decision.evidenceQuality}%`;
    nextSteps = `1. Review the full evidence list catalog.\n2. Follow containment steps.`;
    uncertainty = `Assessment is deterministic. Real-world validation remains subject to SOC analyst review.`;
    emailCase.evidenceList.slice(0, 3).forEach(e => citedIds.push(e.id));
  }

  const answer = `### **Evidence-supported findings**\n${findings}\n\n` +
    `### **Counter-evidence**\n${counter}\n\n` +
    `### **Recommended next steps**\n${nextSteps}\n\n` +
    `### **Uncertainty**\n${uncertainty}\n\n` +
    `### **Evidence IDs used**\n${citedIds.map(id => `[${id}]`).join(', ') || 'None'}`;

  return { answer, citedEvidenceIds: citedIds };
}
